openapi: 3.0.0
info:
  description: Simple Inventory API
  version: 3.0.0
  title: Simple Inventory API
  contact:
    email: mornemaritz@gmail.com

components:
  schemas:
    Product:
      type: object
      required:
        - name
      description: A Product
      properties:
        id:
          type: string
        name:
          type: string
    ProductAction:
      type: string
      enum:
        - add-to-shopping-list
        - remove-from-shopping-list
        - add-to-inventory
        - remove-from-inventory
        - pick
        - unpick
        - pack-away
  parameters:
    top:
      in: query
      required: false
      name: top
      description: The max number of items to returns in a result
      schema:
        type: number
        default: 20
    skip:
      in: query
      required: false
      name: skip
      description: The number of items to skip within the results
      schema:
        type: number
        default: 0
    productId:
      in: path
      required: true
      name: productId
      description: The Product unique identifier
      schema:
        type: string
    action:
      in: query
      required: false
      name: action
      description: The action to be performed on the Product
      schema:
        $ref: "#/components/schemas/ProductAction"

  responses:
    Product:
      description: A Product result
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Product"
    ProductArray:
      description: An array of Products
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "#/components/schemas/Product"

paths:
  /products:
    get:
      operationId: GetProducts
      summary: Gets an array of Products
      tags:
        - Products
      parameters:
        - $ref: "#/components/parameters/top"
        - $ref: "#/components/parameters/skip"
      responses:
        200:
          $ref: "#/components/responses/ProductArray"
  /products/{productId}/actions:
    post:
      operationId: ActOnProduct
      summary: Performs the specified action on the selected product
      tags:
        - Products
      parameters:
        - $ref: "#/components/parameters/productId"
        - $ref: "#/components/parameters/action"
      responses:
        200:
          $ref: "#/components/responses/Product"

